services:
  app:
    build: .
    container_name: histolog-be
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true
