spring.application.name=Histolog-be
spring.profiles.include=oauth

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@db.histolog.app:1521/histologdb
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Allowed Redirect URIs
app.allowed-redirects=http://localhost:8081,https://histolog.app,exp://,http://192.168.0.18:8080

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=604800000

# AI server
ai.server.url=${AI_SERVER_URL:http://127.0.0.1:8000}